### ISSUE TITLE
Stuck on Tutorial - v1.8 from itch.io

### ISSUE THREAD

**Issue by GrowThinky** [Interrupt/delverengine#278]
I downloaded the mac Version from itch.io. However, in the tutorial, every time I die after taking the red orb, the game just puts me back to the beginning of the tutorial again. All i can do in the game is walk the way to the orb, die, and repeat that in an endless loop. 

Am I missing something?

**Comment by joshuaskelly** [comment]
This is a known Mac issue. It happens when the app doesn't have write permissions to the directory it is ran from. Some folks have had success working around this by running the embedded jar directly.

I've tested packaging Delver with a different tool and that does work. So I just need to set up that build process and make new builds.

**Comment by GrowThinky** [comment]
Running delver.jar solved it! Thank you for responding to my issue. I’ll finally try the full game now. Already love how everything looks.

cheers, 
Christoph
